# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IoXOsz2OElBzJ1D555394JBYCSrBYFSw
"""

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Ensure the dataset is downloaded correctly
# Remove any existing heart.csv to ensure a fresh download
!rm -f heart.csv

# This command will download a commonly used heart disease dataset as `heart.csv`
# Using a reliable public source for a pre-cleaned dataset (UCI ML Heart Disease Dataset)
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data -O heart.csv

# The UCI dataset is not perfectly clean; it uses '?' for missing values and has no header.
# Let's load it with appropriate parameters and add column names for clarity.
# Define column names based on common usage for this dataset
column_names = [
    'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
    'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'
]
data = pd.read_csv("heart.csv", names=column_names, na_values='?')

# Handle missing values (e.g., fill with mode or drop rows)
# For simplicity, let's drop rows with missing values for now.
data = data.dropna()

# The original 'target' column has values 0, 1, 2, 3, 4 where >0 indicates heart disease.
# Convert it to a binary classification problem (0 = no disease, 1 = disease).
data['target'] = data['target'].apply(lambda x: 1 if x > 0 else 0)

# Define Features and Target
X = data.drop("target", axis=1)
y = data["target"]

# Split Dataset into Training and Testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create Logistic Regression Model
# Increase max_iter for convergence with this dataset
model = LogisticRegression(max_iter=1000)

# Train the Model
model.fit(X_train_scaled, y_train)

# Make Predictions
y_pred = model.predict(X_test_scaled)

# Model Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Logistic Regression Accuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:", cm)

# Graph for Actual vs Predicted Results
plt.figure(figsize=(6,4))
plt.plot(y_test.values[:30], label="Actual", marker='o')
plt.plot(y_pred[:30], label="Predicted", marker='x')
plt.title("Logistic Regression Prediction Graph")
plt.xlabel("Sample Index")
plt.ylabel("Heart Disease (0 = No, 1 = Yes)")
plt.legend()
plt.show()

from sklearn.ensemble import RandomForestClassifier

# Create Random Forest Classifier model
# Using a random_state for reproducibility
rf_model = RandomForestClassifier(random_state=42)

# Train the Model using scaled data
rf_model.fit(X_train_scaled, y_train)

# Make Predictions
y_pred_rf = rf_model.predict(X_test_scaled)

# Model Accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Classifier Accuracy:", accuracy_rf)

# Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
print("\nConfusion Matrix (Random Forest):\n", cm_rf)

# Graph for Actual vs Predicted Results (Random Forest)
plt.figure(figsize=(6,4))
plt.plot(y_test.values[:30], label="Actual", marker='o')
plt.plot(y_pred_rf[:30], label="Predicted", marker='x')
plt.title("Random Forest Classifier Prediction Graph")
plt.xlabel("Sample Index")
plt.ylabel("Heart Disease (0 = No, 1 = Yes)")
plt.legend()
plt.show()

from sklearn.tree import DecisionTreeClassifier

# Create Decision Tree Classifier model
# Using a random_state for reproducibility
dt_model = DecisionTreeClassifier(random_state=42)

# Train the Model using scaled data
dt_model.fit(X_train_scaled, y_train)

# Make Predictions
y_pred_dt = dt_model.predict(X_test_scaled)

# Model Accuracy
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Classifier Accuracy:", accuracy_dt)

# Confusion Matrix
cm_dt = confusion_matrix(y_test, y_pred_dt)
print("\nConfusion Matrix (Decision Tree):\n", cm_dt)

# Graph for Actual vs Predicted Results (Decision Tree)
plt.figure(figsize=(6,4))
plt.plot(y_test.values[:30], label="Actual", marker='o')
plt.plot(y_pred_dt[:30], label="Predicted", marker='x')
plt.title("Decision Tree Classifier Prediction Graph")
plt.xlabel("Sample Index")
plt.ylabel("Heart Disease (0 = No, 1 = Yes)")
plt.legend()
plt.show()

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


# Define column names based on common usage for this dataset
column_names = [
    'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
    'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'
]

# Load Dataset with column names and handle missing values
data = pd.read_csv("heart.csv", names=column_names, na_values='?')

# Handle missing values (e.g., drop rows)
data = data.dropna()

# The original 'target' column has values 0, 1, 2, 3, 4 where >0 indicates heart disease.
# Convert it to a binary classification problem (0 = no disease, 1 = disease).
data['target'] = data['target'].apply(lambda x: 1 if x > 0 else 0)

print("First 5 Rows of Dataset")
print(data.head())

print("\nDataset Information")
print(data.info())


# Define Features and Target
X = data.drop("target", axis=1)
y = data["target"]


# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Feature Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# Logistic Regression
lr_model = LogisticRegression(max_iter=1000) # Increased max_iter for convergence
lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, lr_pred)

print("\nLogistic Regression Accuracy:", lr_accuracy)
print(confusion_matrix(y_test, lr_pred))
print(classification_report(y_test, lr_pred))


# Decision Tree
dt_model = DecisionTreeClassifier(random_state=42) # Added random_state for reproducibility
dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_pred)

print("\nDecision Tree Accuracy:", dt_accuracy)
print(confusion_matrix(y_test, dt_pred))
print(classification_report(y_test, dt_pred))


# Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42) # Added random_state for reproducibility
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)

print("\nRandom Forest Accuracy:", rf_accuracy)
print(confusion_matrix(y_test, rf_pred))
print(classification_report(y_test, rf_pred))


# Accuracy Comparison Graph
algorithms = ['Logistic Regression', 'Decision Tree', 'Random Forest']
accuracy = [lr_accuracy, dt_accuracy, rf_accuracy]

plt.bar(algorithms, accuracy)
plt.title("Heart Disease Prediction Algorithm Comparison")
plt.xlabel("Algorithms")
plt.ylabel("Accuracy")
plt.show()